name: Maven Build

on:
  push:
    branches:
      - mainline
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Build with Maven
        run: mvn -B clean install test package
      - name: Generate CycloneDX SBOM
        run: mvn cyclonedx:makeBom
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: JAR with sources
          path: |
            target/*.jar
            target/bom.xml
            target/bom.json
      - name: Archive BOM
        uses: actions/upload-artifact@v3
        with:
          name: BOM
          path: target/bom.*
      - name: Archive JavaDoc
        uses: actions/upload-artifact@v3
        with:
          name: JavaDoc
          path: target/site/apidocs
      - name: Archive test results
        uses: actions/upload-artifact@v3
        with:
          name: Test results
          path: |
            target/site/surefire-report.html
            target/surefire-reports/*.xml
  cyclonedx:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run CycloneDX CLI
        uses: docker://cyclonedx/cyclonedx-cli:latest
        with:
          args: analyze --input-file /github/workspace/target/bom.xml --output-format json
      - name: Save CycloneDX report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Cyclone DX report
          path: report.json