name: Maven Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
      - name: Build with Maven
        run: mvn clean install package
      - name: Generate CycloneDX SBOM
        run: mvn cyclonedx:makeAggregateBom
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: maven-build-artifacts
          path: | # Archive build artifacts and SBOM files
            target/*.jar
            bom.xml
            bom.json
      - name: Archive JavaDoc
        uses: actions/upload-artifac@v3
        with:
          name: java-doc-artifacts
          path: target/site/apidocs